server.port=8088
spring.application.name=notification-service

# Database Supabase
spring.datasource.url=jdbc:postgresql://db.qcketqdrqkvgekmgviil.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Thong+0917374532
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ (CloudAMQP - same as other services)
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

# --- CAU HINH GUI EMAIL (GMAIL SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thongnguyen07102004@gmail.com
spring.mail.password=hjqz sqqw stzg kyaa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.minimum-idle=1


# Eureka Discovery
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Zipkin Tracing
management.tracing.sampling.probability=1.0
