# 1. Cấu hình kết nối tới Supabase
spring.datasource.url=jdbc:postgresql://db.qcketqdrqkvgekmgviil.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Thong+0917374532
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.minimum-idle=1

# 2. JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Server & App
server.port=8081
spring.application.name=auth-service

# 4. JWT & Google
jwt.expiration=86400000
google.client.id=29076684294-sjoote056esnibv6de021squum07a2s4.apps.googleusercontent.com

# 5. Redis (Upstash)
spring.data.redis.host=charming-squid-97832.upstash.io
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=true
spring.data.redis.password=gQAAAAAAAX4oAAIgcDFjNjgyZTNhY2JiMWM0ZWMyODMxOGZlNmZhMGRjZjNhNw
spring.data.redis.timeout=1000

# 6. Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thongnguyen07102004@gmail.com
spring.mail.password=hjqz sqqw stzg kyaa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 7. Google ReCAPTCHA
captcha.secret-key=xxxxxxxx_mock_key_for_local_testing

# Eureka Discovery
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Zipkin Tracing
management.tracing.sampling.probability=1.0
