# 1. Supabase Connection
spring.datasource.url=jdbc:postgresql://db.qcketqdrqkvgekmgviil.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Thong+0917374532
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Server
server.port=8086
spring.application.name=inventory-service

# 4. RabbitMQ
spring.rabbitmq.host=capybara.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=kaukagsq
spring.rabbitmq.password=KG1t7O5i45dveYrfTTLu7EmVkB9lwm8v
spring.rabbitmq.virtual-host=kaukagsq


spring.datasource.hikari.maximum-pool-size=1


spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.minimum-idle=1


# Eureka Discovery
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Zipkin Tracing
management.tracing.sampling.probability=1.0
