# 1. Cấu hình kết nối tới Supabase (Đã lấy đúng thông tin từ ảnh của bạn)
spring.datasource.url=jdbc:postgresql://db.qcketqdrqkvgekmgviil.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Thong+0917374532
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Tự động cập nhật bảng trong Database dựa theo Code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Ép Hibernate dùng ngôn ngữ PostgreSQL chuẩn
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Khoá bí mật dùng để "đóng dấu" Token JWT (Bắt buộc phải dài và khó đoán)
jwt.secret=ThuongChoNhungNguoiThichCodeTayNhuBanNhungKhoaNayPhaiDuDaiMoiAnToan123!@#

# Thời gian sống của Token (Ví dụ: 86400000 mili-giây = 24 giờ)
jwt.expiration=86400000

server.port=8082
spring.application.name=product-service

spring.datasource.hikari.maximum-pool-size=1

# 4. In-memory / Redis Caching
# spring.data.redis.host=game-sunbeam-139280.upstash.io
# spring.data.redis.port=6379
# spring.data.redis.ssl.enabled=true
# spring.data.redis.password=gQAAAAAAAiAQAAIgcDExZmYyYjEyYzg3NjU0YzgwYmRlYjk4MTNiMGIzMWJlYg
spring.cache.type=simple

# 5. RabbitMQ
spring.rabbitmq.host=capybara.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=kaukagsq
spring.rabbitmq.password=KG1t7O5i45dveYrfTTLu7EmVkB9lwm8v
spring.rabbitmq.virtual-host=kaukagsq

# 6. Elasticsearch
# spring.elasticsearch.uris=https://my-deployment-58da0b.es.asia-southeast1.gcp.elastic-cloud.com
# spring.elasticsearch.username=elastic
# spring.elasticsearch.password=aqKKreh6TqQDMdpOUfrEkW7o
spring.data.elasticsearch.repositories.enabled=false

# 7. GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.cors.allowed-origins=*

# 8. Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.minimum-idle=1


# Eureka Discovery
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Zipkin Tracing
management.tracing.sampling.probability=1.0
